/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package washingreminder;

import static java.lang.Thread.sleep;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JTextField;
/**
 *
 * @author Ashik
 */
public class NewJFrame3 extends javax.swing.JFrame {

    private static String wn1,wn2,wn3,wn4; 
    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TYPE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 96, 80, 30);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIME LIMIT(D)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 96, 120, 30);

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(153, 96, 80, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("WASHING REMINDER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 11, 270, 61);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(162, 259, 71, 34);

        jButton2.setBackground(new java.awt.Color(153, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 265, 61, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Sets :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(31, 145, 57, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hijab :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(31, 193, 45, 27);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(153, 144, 59, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(153, 194, 59, 29);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 144, 59, 29);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 194, 59, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/washingreminder/Agif.gif"))); // NOI18N
        jLabel8.setText("jLabel2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 11, 30, 37);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/washingreminder/Apic1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    NewJFrame1 a =new NewJFrame1();
    a.setSize(400, 340);
    a.setVisible(true);
    dispose();       
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(evt.getSource()==jButton1)
        {
            try{
                wn1 = jTextField1.getText();
                wn2 = jTextField2.getText();
                wn3 = jTextField3.getText();
                wn4 = jTextField4.getText();
                
                dispose();
                String str= null;
                
                int wnm1,wnm2,wnm3,wnm4;
                
                wnm1=Integer.parseInt(wn1);
                wnm2=Integer.parseInt(wn2);
                wnm3=Integer.parseInt(wn3);
                wnm4=Integer.parseInt(wn4);
                
                int mult1 = wnm1*wnm3;
                int mult2 = wnm2*wnm3;
                
                int avarag=(mult1+mult2)/2;
                
                int x=avarag*24*60*60;
                
                for(int i=0;i<=x;i++)
                {
                    if(i==x)
                    {
                        NewJFrame4 p =new NewJFrame4();
                        p.setSize(400, 340);
                        p.setVisible(true);
                        dispose();
                    }
                    
                    try
                    {
                        sleep(1000);
                    }
                    catch(Exception e)
                    {
                
                    }
                }
                
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame mainFrame3= new NewJFrame3();
            mainFrame3.setSize(400, 340);
            mainFrame3.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
